extend = [
    { path = "./Makefiles/train.toml"},
    { path = "./Makefiles/attack.toml"},
    { path = "./Makefiles/reattack.toml"},
    { path = "./Makefiles/prepross_reattack.toml" }
]

[config]
    skip_core_tasks=true





