[config]
    skip_core_tasks=true

[tasks.train-morimoto-cifar10]
    args=[
        "--batch-size",
        "--dataset",
        "--epochs",
        "--lr",
        "--model",
        "128",
        "1e-2",
        "99",
        "cifar10",
        "morimoto-cifar10",
        "run",
        "src/general_train.py",
    ]
    category="Training"
    command="uv"
    description="Train Morimoto model on CIFAR-10"

[tasks.train-morimoto-mnist]
    args=[
        "--batch-size",
        "--dataset",
        "--epochs",
        "--lr",
        "--model",
        "128",
        "1e-4",
        "99",
        "mnist",
        "morimoto-mnist",
        "run",
        "src/general_train.py",
    ]
    category="Training"
    command="uv"
    description="Train Morimoto model on MNIST"

[tasks.attack-morimoto-mnist-bim]
    args=[
        "--alpha",
        "--attack",
        "--batch-size",
        "--dataset",
        "--epsilon",
        "--model",
        "--n",
        "0.05",
        "0.3",
        "1",
        "10",
        "bim",
        "mnist",
        "morimoto-mnist",
        "run",
        "src/general_ae.py",
    ]
    category="Attacks"
    command="uv"
    description="Attack Morimoto MNIST model with BIM"

[tasks.attack-morimoto-cifar10-bim]
    args=[
        "--alpha",
        "--attack",
        "--batch-size",
        "--dataset",
        "--epsilon",
        "--model",
        "--n",
        "0.05",
        "0.3",
        "10",
        "64",
        "bim",
        "cifar10",
        "morimoto-cifar10",
        "run",
        "src/general_ae.py",
    ]
    category="Attacks"
    command="uv"
    description="Attack Morimoto CIFAR-10 model with BIM"

[tasks.attack-morimoto-cifar10-foolbox-bim]
    args=[
        "--alpha",
        "--attack",
        "--batch-size",
        "--dataset",
        "--epsilon",
        "--model",
        "--n",
        "0.05",
        "0.3",
        "10",
        "64",
        "cifar10",
        "foolbox-bim",
        "morimoto-cifar10",
        "run",
        "src/general_ae.py",
    ]
    category="Attacks"
    command="uv"
    description="Attack Morimoto CIFAR-10 model with BIM"

[tasks.attack-morimoto-cifar10-linf-bim]
    args=[
        "--alpha",
        "--attack",
        "--batch-size",
        "--dataset",
        "--epsilon",
        "--model",
        "--n",
        "0.05",
        "0.3",
        "10",
        "64",
        "cifar10",
        "linf-bim",
        "morimoto-cifar10",
        "run",
        "src/general_ae.py",
    ]
    category="Attacks"
    command="uv"
    description="Attack Morimoto CIFAR-10 model with BIM"

[tasks.attack-morimoto-mnist-foolbox-bim]
    args=[
        "--alpha",
        "--attack",
        "--batch-size",
        "--dataset",
        "--epsilon",
        "--model",
        "--n",
        "0.05",
        "0.3",
        "10",
        "64",
        "foolbox-bim",
        "mnist",
        "morimoto-mnist",
        "run",
        "src/general_ae.py",
    ]
    category="Attacks"
    command="uv"
    description="Attack Morimoto MNIST model with BIM"

[tasks.attack-morimoto-mnist-fgsm]
    args=[
        "--attack",
        "--batch-size",
        "--dataset",
        "--epsilon",
        "--model",
        "0.3",
        "1",
        "fgsm",
        "mnist",
        "morimoto-mnist",
        "run",
        "src/general_ae.py",
    ]
    category="Attacks"
    command="uv"
    description="Attack Morimoto MNIST model with FGSM"

[tasks.attack-sample-ploof]
    args=[
        "--attack",
        "--dataset",
        "--model",
        "fgsm",
        "mnist",
        "ploof",
        "run",
        "src/general_ae.py",
    ]
    category="Attacks"
    command="uv"
    description="Attack Ploof model on MNIST with FGSM"

[tasks.attack-bim-advo]
    args=[
        "--alpha",
        "--attack",
        "--batch-size",
        "--dataset",
        "--epsilon",
        "--model",
        "--n",
        "--num-samples",
        "1",
        "1/255",
        "10",
        "16",
        "8/255",
        "bim",
        "imagenet",
        "inception-v3",
        "run",
        "src/general_ae.py",
    ]
    category="Attacks"
    command="uv"
    description="Attack InceptionV3 model on ImageNet with BIM"
    # バッチサイズが64だとメモリ不足になる

[tasks.attack-foolbox-bim-advo]
    args=[
        "--alpha",
        "--attack",
        "--batch-size",
        "--dataset",
        "--epsilon",
        "--model",
        "--n",
        "--num-samples",
        "1",
        "1/255",
        "10",
        "16",
        "8/255",
        "foolbox-bim",
        "imagenet",
        "inception-v3",
        "run",
        "src/general_ae.py",
    ]
    category="Attacks"
    command="uv"
    description="Attack InceptionV3 model on ImageNet with BIM"
    # バッチサイズが64だとメモリ不足になる
