[project]
name = "re-attack-0806"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch",
    "torchvision",
    "einops",
    "matplotlib",
    "numpy",
    "foolbox>=3.3.4",
    "tqdm>=4.67.1",
    "pandas>=2.3.3",
]

[project.scripts]
# sample-project = "lib:main"
re-attack-0806 = "re_attack_0806:main"

[build-system]
requires = ["uv_build>=0.8.3,<0.9.0"]
build-backend = "uv_build"
