[tasks.reattack-morimoto-cifar10-bim-foolbox-fgsm]
    description="Re-attack Morimoto CIFAR10 model with BIM -> Foolbox FGSM"
    category="Re-Attacks"
    command="uv"
    args=[
        "run",
        "src/general_reattack.py",
        "--dataset",
        "cifar10",
        "--model",
        "morimoto-cifar10",
        "--attack-kind",
        "bim",
        "--attack-eps",
        "0.3",
        "--attack-alpha",
        "0.05",
        "--attack-n",
        "10",
        "--reattack-kind",
        "foolbox-fgsm",
        "--reattack-eps",
        "0.3",
        "--batch-size",
        "128",
    ]


[tasks.reattack-morimoto-cifar10-bim-bim]
    description="Re-attack Morimoto CIFAR10 model with BIM"
    category="Re-Attacks"
    command="uv"
    args=[
        "run",
        "src/general_reattack.py",
        "--dataset",
        "cifar10",
        "--model",
        "morimoto-cifar10",
        "--attack-kind",
        "bim",
        "--attack-eps",
        "0.3",
        "--attack-alpha",
        "0.05",
        "--attack-n",
        "10",
        "--reattack-kind",
        "bim",
        "--reattack-eps",
        "0.3",
        "--reattack-alpha",
        "0.05",
        "--reattack-n",
        "10",
        "--batch-size",
        "128",
    ]

[tasks.reattack-morimoto-cifar10-foolbox-fgsm-foolbox-fgsm]
    description="Re-attack Morimoto CIFAR10 model with Foolbox FGSM -> Foolbox FGSM"
    category="Re-Attacks"
    command="uv"
    args=[
        "run",
        "src/general_reattack.py",
        "--dataset",
        "cifar10",
        "--model",
        "morimoto-cifar10",
        "--attack-kind",
        "foolbox-fgsm",
        "--attack-eps",
        "0.3",
        "--reattack-kind",
        "foolbox-fgsm",
        "--reattack-eps",
        "0.3",
        "--batch-size",
        "128",
    ]

[tasks.reattack-morimoto-cifar10-foolbox-fgsm-bim]
    description="Re-attack Morimoto CIFAR10 model with FGSM -> BIM"
    category="Re-Attacks"
    command="uv"
    args=[
        "run",
        "src/general_reattack.py",
        "--dataset",
        "cifar10",
        "--model",
        "morimoto-cifar10",
        "--attack-kind",
        "foolbox-fgsm",
        "--attack-eps",
        "0.3",
        "--reattack-kind",
        "bim",
        "--reattack-eps",
        "0.3",
        "--reattack-alpha",
        "0.05",
        "--reattack-n",
        "10",
        "--batch-size",
        "128",
    ]

